# ==========================
#  __  __   __  __    ___   
# |  \/  | |  \/  |  / _ \  
# | |\/| | | |\/| | | | | | 
# | |  | | | |  | | | |_| | 
# |_|  |_| |_|  |_|  \___/
# created by Its123Miguel321
# ==========================

# Use {player} to get the player name (This only works on the level up reward)

# ==========================
# COMBAT MMO SETTINGS
# ==========================

# The combat starting amount to level up
combat.start.amount: 25
# How much the start amount multiplies per level (Must be above 1.0 for it to change per level, keep as 1.0 to make it the same per level. If below 1.0 it will be less per each level)
combat.amount.multiplier: 1.2
# The max level for combat
max.combat.level: 25
# The maximum amount the extra damage percentage can go
max.extradamage.percent: 90
# How much gets added to the extra damage percentage per level
added.extradamage.percent: 2
# The mining level up reward (Write a command with out the '/')
combat.levelup.reward: 'give {player} diamond_block 64'

# ==========================
# MINING MMO SETTINGS
# ==========================

# The mining starting amount to level up
mining.start.amount: 250
# How much the start amount multiplies per level
mining.amount.multiplier: 1.5
# The max level for mining
max.mining.level: 25
# The maximum amount the double drop percentage can go
max.doubledrop.percent: 90
# How much gets added to the double drop percentage per level
added.doubledrop.percent: 2
# The mining level up reward (Write a command with out the '/')
mining.levelup.reward: 'give {player} diamond_block 64'
# A list of allowed blocks for mining. To add a block, you need the id and meta. (id:meta)
allowed.mining.blocks:
- '1:0'
- '4:0'
- '14:0'
- '15:0'
- '16:0'
- '21:0'
- '56:0'
- '73:0'
- '129:0'
- '153:0'

# ==========================
# CRAFTING MMO SETTINGS
# ==========================

# The crafting starting amount to level up
crafting.start.amount: 50
# How much the start amount multiplies per level
crafting.amount.multiplier: 1.5
# The max level for crafting
max.crafting.level: 25
# The crafting level up reward (Write a command with out the '/')
crafting.levelup.reward: 'give {player} diamond_block 64'

# ==========================
# TREE CUTTING MMO SETTINGS
# ==========================

# The tree cutting starting amount to level up
treecutting.start.amount: 250
# How much the start amount multiplies per level
treecutting.amount.multiplier: 1.5
# The max level for tree cutting
max.treecutting.level: 25
# The tree cutting level up reward (Write a command with out the '/')
treecutting.levelup.reward: 'give {player} diamond_block 64'

# ==========================
# BUILDING MMO SETTINGS
# ==========================

# The building starting amount to level up
building.start.amount: 250
# How much the start amount multiplies per level
building.amount.multiplier: 1.5
# The max level for building
max.building.level: 25
# The building level up reward (Write a command with out the '/')
building.levelup.reward: 'give {player} diamond_block 64'